title: Omar Boufous
description: PhD student in Game Theory and Machine Learning.
show_downloads: true

# baseurl: "/thomas-bfs" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
# url: "https://thomas-bfs.github.io" # change this to the base hostname & protocol for your site
# url: "http://localhost:4000/thomas-bfs"
baseurl: ""
url: ""
image_path: /assets/images

google_analytics: UA-163435936-1

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
myname: Omar Boufous
author: Omar Boufous
twitter:
  username:
github:
  owner_url: https://github.com/omar-bfs
  owner_name: Omar Boufous
linkedin:
  owner_url: https://www.linkedin.com/in/omar-boufous/
  owner_name: Omar Boufous
googlescholar:
  owner_url: https://scholar.google.com/citations?user=cDeJ1xcAAAAJ&hl=en&oi=ao
  owner_name: Omar Boufous
contact:
  contact_url: mailto:omar.boufous@orange.com


plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'CV', 'Publications', 'Miscellaneous']
# theme: jekyll-theme-cayman-blog
